import type { FlowAlert, NetPremTick, TideSnapshot } from "@/lib/types";
import { tideFromPremiums } from "@/lib/numbers";

function isoDate(offsetDays: number, now = new Date()): string {
  const d = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  d.setUTCDate(d.getUTCDate() + offsetDays);
  return d.toISOString().slice(0, 10);
}

function minutesAgo(mins: number, now = new Date()): string {
  return new Date(now.getTime() - mins * 60_000).toISOString();
}

function chain(ticker: string, expiry: string, type: "call" | "put", strike: number): string {
  const y = expiry.slice(2, 4);
  const m = expiry.slice(5, 7);
  const d = expiry.slice(8, 10);
  const side = type === "call" ? "C" : "P";
  const strikeCode = Math.round(strike * 1000).toString().padStart(8, "0");
  return `${ticker}${y}${m}${d}${side}${strikeCode}`;
}

function alert(partial: Omit<FlowAlert, "option_chain"> & { option_chain?: string }): FlowAlert {
  return {
    ...partial,
    option_chain:
      partial.option_chain ??
      chain(partial.ticker, partial.expiry, partial.type, Number(partial.strike)),
  };
}

export function buildMockAlerts(now = new Date()): FlowAlert[] {
  const d0 = isoDate(0, now);
  const d1 = isoDate(1, now);
  const d8 = isoDate(8, now);
  const d14 = isoDate(14, now);
  const d21 = isoDate(21, now);
  const d35 = isoDate(35, now);
  const d44 = isoDate(44, now);
  const d90 = isoDate(90, now);

  return [
    alert({
      id: "mock-nvda-sweep",
      ticker: "NVDA",
      type: "call",
      strike: "180",
      expiry: d21,
      price: "9.40",
      bid: "9.30",
      ask: "9.45",
      underlying_price: "176.20",
      created_at: minutesAgo(6, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: true,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: true,
      issue_type: "Common Stock",
      marketcap: 4_300_000_000_000,
      open_interest: 18420,
      total_ask_side_prem: "1284000",
      total_bid_side_prem: "82000",
      total_premium: "1410000",
      total_size: 1500,
      trade_count: 28,
      volume: 61200,
      volume_oi_ratio: "3.32",
    }),
    alert({
      id: "mock-meta-floor",
      ticker: "META",
      type: "call",
      strike: "620",
      expiry: d35,
      price: "18.70",
      bid: "18.50",
      ask: "18.80",
      underlying_price: "598.40",
      created_at: minutesAgo(14, now),
      alert_rule: "FloorTradeLargeCap",
      all_opening_trades: true,
      has_floor: true,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: false,
      issue_type: "Common Stock",
      marketcap: 1_500_000_000_000,
      open_interest: 9200,
      total_ask_side_prem: "742000",
      total_bid_side_prem: "41000",
      total_premium: "812000",
      total_size: 434,
      trade_count: 6,
      volume: 14800,
      volume_oi_ratio: "1.61",
    }),
    alert({
      id: "mock-amd-puts",
      ticker: "AMD",
      type: "put",
      strike: "140",
      expiry: d14,
      price: "4.85",
      bid: "4.75",
      ask: "4.90",
      underlying_price: "152.10",
      created_at: minutesAgo(9, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: true,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: true,
      issue_type: "Common Stock",
      marketcap: 245_000_000_000,
      open_interest: 22100,
      total_ask_side_prem: "510000",
      total_bid_side_prem: "38000",
      total_premium: "564000",
      total_size: 1160,
      trade_count: 41,
      volume: 48200,
      volume_oi_ratio: "2.18",
    }),
    alert({
      id: "mock-aapl-ask",
      ticker: "AAPL",
      type: "call",
      strike: "240",
      expiry: d44,
      price: "6.15",
      bid: "6.05",
      ask: "6.20",
      underlying_price: "228.90",
      created_at: minutesAgo(22, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: true,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: true,
      issue_type: "Common Stock",
      marketcap: 3_400_000_000_000,
      open_interest: 41000,
      total_ask_side_prem: "388000",
      total_bid_side_prem: "54000",
      total_premium: "452000",
      total_size: 735,
      trade_count: 19,
      volume: 39000,
      volume_oi_ratio: "0.95",
    }),
    alert({
      id: "mock-tsla-mixed",
      ticker: "TSLA",
      type: "call",
      strike: "260",
      expiry: d8,
      price: "7.80",
      bid: "7.65",
      ask: "7.90",
      underlying_price: "248.30",
      created_at: minutesAgo(4, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: false,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: true,
      issue_type: "Common Stock",
      marketcap: 790_000_000_000,
      open_interest: 33000,
      total_ask_side_prem: "210000",
      total_bid_side_prem: "165000",
      total_premium: "402000",
      total_size: 515,
      trade_count: 33,
      volume: 28000,
      volume_oi_ratio: "0.85",
    }),
    alert({
      id: "mock-spy-0dte",
      ticker: "SPY",
      type: "call",
      strike: "565",
      expiry: d0,
      price: "1.12",
      bid: "1.10",
      ask: "1.14",
      underlying_price: "562.40",
      created_at: minutesAgo(3, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: true,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: true,
      issue_type: "ETF",
      marketcap: 550_000_000_000,
      open_interest: 120000,
      total_ask_side_prem: "186000",
      total_bid_side_prem: "22000",
      total_premium: "214000",
      total_size: 1910,
      trade_count: 88,
      volume: 410000,
      volume_oi_ratio: "3.41",
    }),
    alert({
      id: "mock-qqq-lottery",
      ticker: "QQQ",
      type: "put",
      strike: "470",
      expiry: d1,
      price: "0.84",
      bid: "0.82",
      ask: "0.86",
      underlying_price: "478.10",
      created_at: minutesAgo(8, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: false,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: true,
      issue_type: "ETF",
      marketcap: 280_000_000_000,
      open_interest: 64000,
      total_ask_side_prem: "41000",
      total_bid_side_prem: "9000",
      total_premium: "54000",
      total_size: 640,
      trade_count: 24,
      volume: 91000,
      volume_oi_ratio: "1.42",
    }),
    alert({
      id: "mock-coin-bid",
      ticker: "COIN",
      type: "call",
      strike: "280",
      expiry: d21,
      price: "11.20",
      bid: "11.05",
      ask: "11.35",
      underlying_price: "262.00",
      created_at: minutesAgo(18, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: false,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: false,
      issue_type: "Common Stock",
      marketcap: 64_000_000_000,
      open_interest: 8700,
      total_ask_side_prem: "48000",
      total_bid_side_prem: "226000",
      total_premium: "291000",
      total_size: 260,
      trade_count: 11,
      volume: 6400,
      volume_oi_ratio: "0.74",
    }),
    alert({
      id: "mock-smci-tiny",
      ticker: "SMCI",
      type: "call",
      strike: "50",
      expiry: d8,
      price: "1.05",
      bid: "1.00",
      ask: "1.10",
      underlying_price: "46.80",
      created_at: minutesAgo(11, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: false,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: false,
      issue_type: "Common Stock",
      marketcap: 27_000_000_000,
      open_interest: 19000,
      total_ask_side_prem: "9200",
      total_bid_side_prem: "3100",
      total_premium: "14200",
      total_size: 135,
      trade_count: 7,
      volume: 4200,
      volume_oi_ratio: "0.22",
    }),
    alert({
      id: "mock-arm-multi",
      ticker: "ARM",
      type: "call",
      strike: "160",
      expiry: d35,
      price: "8.40",
      bid: "8.20",
      ask: "8.50",
      underlying_price: "148.60",
      created_at: minutesAgo(27, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: false,
      has_floor: false,
      has_multileg: true,
      has_singleleg: false,
      has_sweep: false,
      issue_type: "ADR",
      marketcap: 155_000_000_000,
      open_interest: 5400,
      total_ask_side_prem: "118000",
      total_bid_side_prem: "101000",
      total_premium: "246000",
      total_size: 293,
      trade_count: 4,
      volume: 3100,
      volume_oi_ratio: "0.57",
    }),
    alert({
      id: "mock-avgo-open",
      ticker: "AVGO",
      type: "call",
      strike: "200",
      expiry: d21,
      price: "7.55",
      bid: "7.45",
      ask: "7.60",
      underlying_price: "188.20",
      created_at: minutesAgo(16, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: true,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: true,
      issue_type: "Common Stock",
      marketcap: 880_000_000_000,
      open_interest: 11200,
      total_ask_side_prem: "605000",
      total_bid_side_prem: "44000",
      total_premium: "672000",
      total_size: 890,
      trade_count: 21,
      volume: 27400,
      volume_oi_ratio: "2.45",
    }),
    alert({
      id: "mock-msft-floor-put",
      ticker: "MSFT",
      type: "put",
      strike: "420",
      expiry: d44,
      price: "6.90",
      bid: "6.80",
      ask: "7.00",
      underlying_price: "438.50",
      created_at: minutesAgo(31, now),
      alert_rule: "FloorTradeLargeCap",
      all_opening_trades: true,
      has_floor: true,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: false,
      issue_type: "Common Stock",
      marketcap: 3_200_000_000_000,
      open_interest: 15800,
      total_ask_side_prem: "334000",
      total_bid_side_prem: "27000",
      total_premium: "371000",
      total_size: 538,
      trade_count: 5,
      volume: 12100,
      volume_oi_ratio: "0.77",
    }),
    alert({
      id: "mock-amzn-long",
      ticker: "AMZN",
      type: "call",
      strike: "240",
      expiry: d90,
      price: "14.10",
      bid: "13.90",
      ask: "14.20",
      underlying_price: "221.40",
      created_at: minutesAgo(41, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: true,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: false,
      issue_type: "Common Stock",
      marketcap: 2_300_000_000_000,
      open_interest: 8600,
      total_ask_side_prem: "198000",
      total_bid_side_prem: "22000",
      total_premium: "231000",
      total_size: 164,
      trade_count: 8,
      volume: 4100,
      volume_oi_ratio: "0.48",
    }),
    alert({
      id: "mock-pltr-fight",
      ticker: "PLTR",
      type: "put",
      strike: "30",
      expiry: d21,
      price: "1.42",
      bid: "1.38",
      ask: "1.45",
      underlying_price: "34.80",
      created_at: minutesAgo(12, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: true,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: true,
      issue_type: "Common Stock",
      marketcap: 78_000_000_000,
      open_interest: 54000,
      total_ask_side_prem: "276000",
      total_bid_side_prem: "18000",
      total_premium: "301000",
      total_size: 2120,
      trade_count: 36,
      volume: 88000,
      volume_oi_ratio: "1.63",
    }),
    alert({
      id: "mock-cost-quality",
      ticker: "COST",
      type: "call",
      strike: "980",
      expiry: d35,
      price: "16.40",
      bid: "16.20",
      ask: "16.50",
      underlying_price: "952.10",
      created_at: minutesAgo(38, now),
      alert_rule: "FloorTradeLargeCap",
      all_opening_trades: true,
      has_floor: true,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: true,
      issue_type: "Common Stock",
      marketcap: 420_000_000_000,
      open_interest: 2100,
      total_ask_side_prem: "492000",
      total_bid_side_prem: "19000",
      total_premium: "528000",
      total_size: 322,
      trade_count: 9,
      volume: 5400,
      volume_oi_ratio: "2.57",
    }),
    alert({
      id: "mock-hood-lotto",
      ticker: "HOOD",
      type: "call",
      strike: "25",
      expiry: d0,
      price: "0.32",
      bid: "0.30",
      ask: "0.34",
      underlying_price: "23.10",
      created_at: minutesAgo(2, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: false,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: true,
      issue_type: "Common Stock",
      marketcap: 20_000_000_000,
      open_interest: 41000,
      total_ask_side_prem: "11800",
      total_bid_side_prem: "2400",
      total_premium: "16400",
      total_size: 512,
      trade_count: 22,
      volume: 63000,
      volume_oi_ratio: "1.54",
    }),
    alert({
      id: "mock-crm-mid",
      ticker: "CRM",
      type: "put",
      strike: "250",
      expiry: d14,
      price: "5.10",
      bid: "5.00",
      ask: "5.15",
      underlying_price: "261.80",
      created_at: minutesAgo(25, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: true,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: true,
      issue_type: "Common Stock",
      marketcap: 250_000_000_000,
      open_interest: 7600,
      total_ask_side_prem: "188000",
      total_bid_side_prem: "21000",
      total_premium: "219000",
      total_size: 430,
      trade_count: 14,
      volume: 9800,
      volume_oi_ratio: "1.29",
    }),
    alert({
      id: "mock-intc-bidput",
      ticker: "INTC",
      type: "put",
      strike: "22",
      expiry: d8,
      price: "0.68",
      bid: "0.66",
      ask: "0.70",
      underlying_price: "23.40",
      created_at: minutesAgo(19, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: false,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: false,
      issue_type: "Common Stock",
      marketcap: 102_000_000_000,
      open_interest: 88000,
      total_ask_side_prem: "16000",
      total_bid_side_prem: "94000",
      total_premium: "118000",
      total_size: 1740,
      trade_count: 18,
      volume: 22000,
      volume_oi_ratio: "0.25",
    }),
    alert({
      id: "mock-snow-a",
      ticker: "SNOW",
      type: "call",
      strike: "130",
      expiry: d14,
      price: "4.20",
      bid: "4.10",
      ask: "4.25",
      underlying_price: "128.40",
      created_at: minutesAgo(38, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: true,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: true,
      issue_type: "Common Stock",
      marketcap: 42_000_000_000,
      open_interest: 4100,
      total_ask_side_prem: "62000",
      total_bid_side_prem: "8000",
      total_premium: "72000",
      total_size: 170,
      trade_count: 11,
      volume: 5200,
      volume_oi_ratio: "1.27",
    }),
    alert({
      id: "mock-snow-b",
      ticker: "SNOW",
      type: "call",
      strike: "130",
      expiry: d14,
      price: "4.35",
      bid: "4.25",
      ask: "4.40",
      underlying_price: "128.55",
      created_at: minutesAgo(22, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: true,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: false,
      issue_type: "Common Stock",
      marketcap: 42_000_000_000,
      open_interest: 4100,
      option_chain: chain("SNOW", d14, "call", 130),
      total_ask_side_prem: "48000",
      total_bid_side_prem: "6000",
      total_premium: "56000",
      total_size: 128,
      trade_count: 9,
      volume: 6100,
      volume_oi_ratio: "1.49",
    }),
    alert({
      id: "mock-snow-c",
      ticker: "SNOW",
      type: "call",
      strike: "135",
      expiry: d21,
      price: "3.10",
      bid: "3.00",
      ask: "3.15",
      underlying_price: "128.60",
      created_at: minutesAgo(11, now),
      alert_rule: "RepeatedHitsAscendingFill",
      all_opening_trades: true,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: true,
      issue_type: "Common Stock",
      marketcap: 42_000_000_000,
      open_interest: 2800,
      total_ask_side_prem: "41000",
      total_bid_side_prem: "4000",
      total_premium: "46000",
      total_size: 148,
      trade_count: 10,
      volume: 3900,
      volume_oi_ratio: "1.39",
    }),
    alert({
      id: "mock-crwd-a",
      ticker: "CRWD",
      type: "call",
      strike: "320",
      expiry: d21,
      price: "6.40",
      bid: "6.30",
      ask: "6.50",
      underlying_price: "318.20",
      created_at: minutesAgo(44, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: true,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: true,
      issue_type: "Common Stock",
      marketcap: 78_000_000_000,
      open_interest: 3600,
      total_ask_side_prem: "88000",
      total_bid_side_prem: "11000",
      total_premium: "99000",
      total_size: 155,
      trade_count: 12,
      volume: 4800,
      volume_oi_ratio: "1.33",
    }),
    alert({
      id: "mock-crwd-b",
      ticker: "CRWD",
      type: "call",
      strike: "320",
      expiry: d21,
      price: "6.55",
      bid: "6.45",
      ask: "6.60",
      underlying_price: "318.40",
      created_at: minutesAgo(21, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: true,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: false,
      issue_type: "Common Stock",
      marketcap: 78_000_000_000,
      open_interest: 3600,
      total_ask_side_prem: "54000",
      total_bid_side_prem: "7000",
      total_premium: "61000",
      total_size: 93,
      trade_count: 8,
      volume: 5400,
      volume_oi_ratio: "1.50",
    }),
    alert({
      id: "mock-crwd-c",
      ticker: "CRWD",
      type: "put",
      strike: "280",
      expiry: d14,
      price: "4.80",
      bid: "4.70",
      ask: "4.90",
      underlying_price: "318.50",
      created_at: minutesAgo(16, now),
      alert_rule: "RepeatedHits",
      all_opening_trades: true,
      has_floor: false,
      has_multileg: false,
      has_singleleg: true,
      has_sweep: true,
      issue_type: "Common Stock",
      marketcap: 78_000_000_000,
      open_interest: 2100,
      total_ask_side_prem: "8000",
      total_bid_side_prem: "72000",
      total_premium: "81000",
      total_size: 168,
      trade_count: 9,
      volume: 2600,
      volume_oi_ratio: "1.24",
    }),
  ];
}

export function buildMockTide(now = new Date()): TideSnapshot {
  return tideFromPremiums(4_820_000, 1_640_000, now.toISOString());
}

export function buildMockTickerTides(): Record<string, TideSnapshot> {
  return {
    NVDA: tideFromPremiums(1_240_000, 210_000, null),
    META: tideFromPremiums(420_000, 90_000, null),
    AMD: tideFromPremiums(80_000, 310_000, null),
    AAPL: tideFromPremiums(510_000, 180_000, null),
    TSLA: tideFromPremiums(190_000, 205_000, null),
    SPY: tideFromPremiums(2_100_000, 2_400_000, null),
    QQQ: tideFromPremiums(880_000, 1_020_000, null),
    COIN: tideFromPremiums(40_000, 95_000, null),
    AVGO: tideFromPremiums(360_000, 70_000, null),
    MSFT: tideFromPremiums(290_000, 410_000, null),
    PLTR: tideFromPremiums(410_000, 60_000, null),
    COST: tideFromPremiums(150_000, 40_000, null),
    CRM: tideFromPremiums(55_000, 140_000, null),
    AMZN: tideFromPremiums(220_000, 90_000, null),
    SNOW: tideFromPremiums(95_000, 28_000, null),
    CRWD: tideFromPremiums(120_000, 35_000, null),
  };
}

export function buildMockNetPremTicks(ticker: string, now = new Date()): NetPremTick[] {
  const tides = buildMockTickerTides();
  const tide = tides[ticker] ?? tideFromPremiums(80_000, 40_000, null);
  const ticks: NetPremTick[] = [];
  for (let i = 30; i >= 0; i -= 1) {
    const t = new Date(now.getTime() - i * 60_000);
    const progress = (30 - i) / 30;
    const jitter = Math.sin(i / 3) * 0.08;
    ticks.push({
      date: t.toISOString().slice(0, 10),
      tape_time: t.toISOString(),
      net_call_premium: String(Math.round(tide.netCallPremium * (0.4 + progress * 0.6 + jitter))),
      net_put_premium: String(Math.round(tide.netPutPremium * (0.4 + progress * 0.6 - jitter))),
      net_call_volume: Math.round(400 + progress * 800),
      net_put_volume: Math.round(200 + progress * 350),
    });
  }
  return ticks;
}
